# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RJv-mEVyTWO6OUu9muiz1SN5YT-480_l
"""

#Resolução da Lista 3 de Cálculo Numérico
#Lista 3 - Questão 8
#David Nicacio

#Letra A - Resolução Gráfica

#Bibliotecas Necessárias

import numpy as np
import matplotlib.pyplot as plt

#Função
x = np.linspace(-1,1)
f_x = 2*(x**3)-11.7*(x**2) + 17.7*x-5

#Plotagem do Gráfico

plt.plot(x,f_x)
plt.xlabel('X')
plt.ylabel('Y')
plt.show()